services:
  calibre:
    image: linuxserver/calibre:9.14.0
    container_name: calibre
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/homelab/calibre:/config:rw
    networks:
      - proxy
    shm_size: "1gb"
    restart: unless-stopped
    labels:
      #Traefik
      - traefik.enable=true
      ## Calibre Web Server
      - traefik.http.services.calibre.loadbalancer.server.port=8081
      - traefik.http.routers.calibre.rule=Host(`calibre.homelab`)
      - traefik.http.routers.calibre.service=calibre
      - traefik.http.routers.calibre.entrypoints=websecure
      ## Calibre Desktop GUI
      - traefik.http.services.calibre-desktop.loadbalancer.server.port=8080
      - traefik.http.routers.calibre-desktop.rule=Host(`calibre-desktop.homelab`)
      - traefik.http.routers.calibre-desktop.service=calibre-desktop
      - traefik.http.routers.calibre-desktop.entrypoints=websecure
      # Homepage
      ## Calibre Web Server - Moved to services.yaml
      # - homepage.group=Media
      # - homepage.name=Calibre
      # - homepage.icon=calibre.png
      # - homepage.href=https://calibre.homelab
      # - homepage.description=E-book Library Web Server
      # Calibre Desktop
      - homepage.group=Media
      - homepage.name=Calibre Desktop
      - homepage.icon=calibre.png
      - homepage.href=https://calibre-desktop.homelab
      - homepage.description=E-book Library Desktop GUI

  shelfmark:
    image: ghcr.io/calibrain/shelfmark:v1.3.15
    container_name: shelfmark
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /srv/homelab/calibre/shelfmark_config:/config:rw
      - /srv/homelab/calibre/downloads:/books:rw
    networks:
      - proxy
    restart: unless-stopped
    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.services.shelfmark.loadbalancer.server.port=8084
      - traefik.http.routers.shelfmark.rule=Host(`shelfmark.homelab`)
      - traefik.http.routers.shelfmark.service=shelfmark
      - traefik.http.routers.shelfmark.entrypoints=websecure
      # Homepage
      - homepage.group=Media
      - homepage.name=Shelfmark
      - homepage.icon=shelfmark.png
      - homepage.href=https://shelfmark.homelab
      - homepage.description=E-book Download Manager

networks:
  proxy:
    external: true
