services:
  jenkins:
    image: jenkins/jenkins:2.555.1-lts
    container_name: jenkins
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - jenkins_home:/var/jenkins_home:rw
    labels:
      # Traefik
      - traefik.enable=true
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
      - traefik.http.routers.jenkins.rule=Host(`jenkins.homelab`)
      - traefik.http.routers.jenkins.service=jenkins
      - traefik.http.routers.jenkins.entrypoints=websecure
      # Homepage
      - homepage.group=Development
      - homepage.name=Jenkins
      - homepage.icon=jenkins.png
      - homepage.href=https://jenkins.homelab
      - homepage.description=CI/CD Pipeline Server

volumes:
  jenkins_home:

networks:
  proxy:
    external: true