services:
  nexus:
    image: sonatype/nexus3:3.91.1
    container_name: nexus
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - NEXUS_SECURITY_INITIAL_PASSWORD=${NEXUS_ADMIN_PASSWORD}
    volumes:
      - nexus_data:/nexus-data:rw
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
      - "traefik.http.routers.nexus.rule=Host(`nexus.homelab`)"
      - "traefik.http.routers.nexus.service=nexus"
      - "traefik.http.routers.nexus.entrypoints=websecure"
      - "traefik.http.routers.nexus.tls=true"
      # Homepage
      - "homepage.group=Development"
      - "homepage.name=Nexus"
      - "homepage.icon=nexus.png"
      - "homepage.href=https://nexus.homelab"
      - "homepage.description=Repository Manager"

volumes:
  nexus_data:

networks:
  proxy:
    external: true
