services:
  glance:
    image: glanceapp/glance:v0.8.4
    container_name: glance
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /srv/homelab/glance/config:/app/config:ro
      - /srv/homelab/glance/assets:/app/assets:ro
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
      - "traefik.http.routers.glance.rule=Host(`glance.homelab`)"
      - "traefik.http.routers.glance.service=glance"
      - "traefik.http.routers.glance.entrypoints=websecure"
      - "traefik.http.routers.glance.tls=true"
      # Homepage
      - "homepage.group=Infrastructure"
      - "homepage.name=Glance"
      - "homepage.icon=glance.png"
      - "homepage.href=http://glance.homelab"
      - "homepage.description=Dashboard"

networks:
  proxy:
    external: true
